### PR TITLE
Try this?

### PR DESCRIPTION
**Pull request by SnapDragon7410**
Plz

### CODE REVIEW

**Comment by penn5** [comment]
What the fuck?

**Comment by SnapDragon7410** [comment]
Y didnt u try it

**Comment by penn5** [comment]
@SnapDragon7410 fuck off.

**Comment by SpEcHiDe** [comment]
@SnapDragon7410 just COPY PASTING won't make it run. 😐

**Comment by AvinashReddy3108** [comment]
> @SnapDragon7410 just COPY PASTING won't make it run.

True, closing the issue before things go out of hand.

**Comment by penn5** [comment]
> > @SnapDragon7410 just COPY PASTING won't make it run.
> 
> True, closing the issue before things go out of hand.

I closed it a month ago :rofl:

**Pull request closed without merging**
