### PR TITLE
Gitupload module update

### PR DESCRIPTION
**Pull request by erenmetesar**
added the feature to specify what repo to upload to both in cmd and vars, if user states the repo name in here it will automatically upload in it, if he wants to state it in the cmd he can do .commit <reponame>

### CODE REVIEW

**Comment by penn5** [comment]
Don't delete the old variable name

**Comment by erenmetesar** [comment]
i literally fucking added 2 vars in the compat fuck github idc

**Comment by penn5** [comment]
And you deleted one. Don't delete it!

**Comment by penn5** [comment]
Fix lint

**Comment by erenmetesar** [comment]
i fixed it

**Pull request merged**
